# Generated by Django 5.0 on 2024-01-31 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Widget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("location", models.CharField(max_length=255)),
                ("longitude", models.FloatField()),
                ("latitude", models.FloatField()),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="widgets",
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Widget",
                "verbose_name_plural": "Widgets",
                "db_table": "widgets",
                "ordering": ("location", "profile__user__username"),
            },
        ),
    ]
