# Generated by Django 5.0 on 2024-02-01 21:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="widget",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="widget",
            name="longitude",
        ),
    ]
