# Generated by Django 5.0 on 2024-01-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JeopardyQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("show_number", models.IntegerField()),
                ("air_date", models.DateField()),
                ("round", models.CharField(max_length=50)),
                ("category", models.CharField(max_length=255)),
                ("value", models.FloatField(null=True)),
                ("question", models.TextField()),
                ("answer", models.TextField()),
            ],
            options={
                "db_table": "jeopardy_questions",
                "ordering": ["-show_number", "air_date"],
            },
        ),
    ]
