# Generated by Django 5.0 on 2024-01-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jeopardy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jeopardyquestion",
            name="air_date",
            field=models.CharField(max_length=50),
        ),
    ]
